# image will be published to ghcr.io/<user>/<name>
name: custom-ublue-formile
# description will be included in the image's metadata
description: Personal ublue image with some custom configuration

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - tlp
      - tlp-rdw
      - splix
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - power-profiles-daemon
  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - ublue-os-wallpapers
      # - ublue-update # https://github.com/ublue-os/ublue-update
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm


#  - type: yafti # if included, yafti and it's dependencies (pip & libadwaita)
#                #  will be installed and set up
#    custom-flatpaks: # this section is optional
#      # - Celluloid: io.github.celluloid_player.Celluloid
#      # - Krita: org.kde.krita

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
      - tlp_post_install.sh
